// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhjpcpuslssnngrmcbgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oanBjcHVzbHNzbm5ncm1jYmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTMyMjcsImV4cCI6MjA2OTY4OTIyN30.cKt9ER65Ao0bQ2QAprzd5j-xlFkq-tqu0wVrqF8oTGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});